insert into books(id, name, image, genre, copies_sold, author_id, price, synopsis)
values
(0, 'Misery', 'https://upload.wikimedia.org/wikipedia/en/6/6f/Stephen_King_Misery_cover.jpg', 'Horror', 875000, 1, 8.99, 'Paul Sheldon. He''s a bestselling novelist who has finally met his biggest fan. Her name is Annie Wilkes and she is more than a rabid reader - she is Paul''s nurse, tending his shattered body after an automobile accident. But she is also his captor, keeping him prisoner in her isolated house.'),
(0, 'Harry Potter and The Philosopher''s Stone', 'https://www.abebooks.com/images/books/harry-potter/philosophers-stone.jpg', 'Fantasy', 500000000, 2, 4.99, 'Harry Potter''s life is miserable. His parents are dead and he''s stuck with his heartless relatives, who force him to live in a tiny closet under the stairs. But his fortune changes when he receives a letter that tells him the truth about himself: he''s a wizard. A mysterious visitor rescues him from his relatives and takes him to his new home, Hogwarts School of Witchcraft and Wizardry.'),
(0, 'The Fault In Our Stars', 'https://upload.wikimedia.org/wikipedia/en/a/a9/The_Fault_in_Our_Stars.jpg', 'Romance', 10700000, 3, 6.99, 'Despite the tumor-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal, her final chapter inscribed upon diagnosis. But when a gorgeous plot twist named Augustus Waters suddenly appears at Cancer Kid Support Group, Hazel''s story is about to be completely rewritten.'),
(0, 'A Brief History Of Time', 'https://images-na.ssl-images-amazon.com/images/I/51slEJbyEmL._AC_SY400_.jpg', 'Science', 10000000, 4, 7.99, 'In the ten years since its publication in 1988, Stephen Hawking''s classic work has become a landmark volume in scientific writing, with more than nine million copies in forty languages sold worldwide. That edition was on the cutting edge of what was then known about the origins and nature of the universe. But the intervening years have seen extraordinary advances in the technology of observing both the micro- and the macrocosmic worlds. These observations have confirmed many of Professor Hawking''s theoretical predictions in the first edition of his book, including the recent discoveries of the Cosmic Background Explorer satellite (COBE), which probed back in time to within 300,000 years of the universe''s beginning and revealed wrinkles in the fabric of space-time that he had projected.'),
(0, 'Looking For Alaska', 'https://images-na.ssl-images-amazon.com/images/I/91nTClkODkL.jpg', 'Romance', 5388, 3, 7.39, 'Before. Miles “Pudge” Halter is done with his safe life at home. His whole life has been one big non-event, and his obsession with famous last words has only made him crave “the Great Perhaps” even more (Francois Rabelais, poet). He heads off to the sometimes crazy and anything-but-boring world of Culver Creek Boarding School, and his life becomes the opposite of safe. Because down the hall is Alaska Young. The gorgeous, clever, funny, sexy, self-destructive, screwed up, and utterly fascinating Alaska Young. She is an event unto herself. She pulls Pudge into her world, launches him into the Great Perhaps, and steals his heart. Then. . . . After. Nothing is ever the same.'),
(0, 'The Stranger', 'https://images-na.ssl-images-amazon.com/images/I/81rNFIU-FxL.jpg', 'Philosophy', 4400, 5, 8.17, 'Through the story of an ordinary man unwittingly drawn into a senseless murder on an Algerian beach, Camus explored what he termed "the nakedness of man faced with the absurd." First published in English in 1946; now in a new translation by Matthew Ward.'),
(0, 'The Giver', 'https://cdn.waterstones.com/bookjackets/large/9780/0072/9780007263516.jpg', 'Philosophy', 12000000, 6, 4.49, 'The Giver, the 1994 Newbery Medal winner, has become one of the most influential novels of our time. The haunting story centers on twelve-year-old Jonas, who lives in a seemingly ideal, if colorless, world of conformity and contentment. Not until he is given his life assignment as the Receiver of Memory does he begin to understand the dark, complex secrets behind his fragile community.'),
(0, 'Lord Of The Flies', 'https://images-na.ssl-images-amazon.com/images/I/81jlbxMyR4L.jpg', 'Philosophy', 25000000, 7, 5.79, 'At the dawn of the next world war, a plane crashes on an uncharted island, stranding a group of schoolboys. At first, with no adult supervision, their freedom is something to celebrate; this far from civilization the boys can do anything they want. Anything. They attempt to forge their own society, failing, however, in the face of terror, sin and evil. And as order collapses, as strange howls echo in the night, as terror begins its reign, the hope of adventure seems as far from reality as the hope of being rescued.”'),
(0, 'The Catcher In The Rye', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1554406349l/7178._SY475_.jpg', 'Philosophy', 65000000, 8, 4.99, 'The hero-narrator of The Catcher in the Rye is an ancient child of sixteen, a native New Yorker named Holden Caulfield. Through circumstances that tend to preclude adult, secondhand description, he leaves his prep school in Pennsylvania and goes underground in New York City for three days. The boy himself is at once too simple and too complex for us to make any final comment about him or his story. Perhaps the safest thing we can say about Holden is that he was born in the world not just strongly attracted to beauty but, almost, hopelessly impaled on it.'),
(0, 'The Light Between Oceans', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1385609251l/19012815.jpg', 'Philosophy', 3000000, 9, 7.49, 'Australia, 1926. After four harrowing years fighting on the Western Front, Tom Sherbourne returns home to take a job as the lighthouse keeper on Janus Rock, nearly half a day''s journey from the coast. To this isolated island, where the supply boat comes once a season and shore leaves are granted every other year at best, Tom brings a young, bold, and loving wife, Isabel. Years later, after two miscarriages and one stillbirth, the grieving Isabel hears a baby''s cries on the wind. A boat has washed up onshore carrying a dead man and a living baby.')
;

insert into authors(id, first_name, last_name, resume)
values
(1, 'Stephen', 'King', 'stephen king resume'),
(2, 'J.K.', 'Rowling', 'famous for harry potter books'),
(3, 'John', 'Green', 'john green resume'),
(4, 'Stephen', 'Hawking', 'stephen hawking resume'),
(5, 'Albert', 'Camus', 'albert camus resume'),
(6, 'Lois', 'Lowry', 'Lois lowry resume'),
(7, 'William', 'Golding', 'william golding resume'),
(8, 'JD', 'Salinger', 'JD salinger resume'),
(9, 'ML', 'Stedman', 'ML Stedman resume')
;

select * from bookshop.books;